### Register Admin
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "username": "admin1",
  "email": "admin1@example.com",
  "password": "password123"
}

###

### Login Admin
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "email": "admin1@example.com",
  "password": "password123"
}

###

### Refresh Token
GET http://localhost:5000/api/token
Accept: application/json
# Pastikan cookie refreshToken sudah tersimpan oleh REST Client

###

### Get Users (Protected)
GET http://localhost:5000/api/vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYWRtaW4xIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3OTExMjEzLCJleHAiOjE3NDc5MTIxMTN9.z2o3j6UvX9Umqg0d9oM8HhOBt1oGy_ItsRFS69Oh9IE
###

### Logout
DELETE http://localhost:5000/api/logout



###
### Get All Vehicles (Protected)
GET http://localhost:5000/api/vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYWRtaW4xIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3OTE3OTY4LCJleHAiOjE3NDc5MTg4Njh9.K32PnMerY3H2zzJ3QqvGMbmPI0j_zxnaraEUYd2NDj8

###

### Get Vehicle By ID (Protected)
GET http://localhost:5000/api/vehicles/1
Authorization: Bearer 

###

### Create New Vehicle (Protected)
POST http://localhost:5000/api/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYWRtaW4xIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3OTE3OTY4LCJleHAiOjE3NDc5MTg4Njh9.K32PnMerY3H2zzJ3QqvGMbmPI0j_zxnaraEUYd2NDj8

{
  "name": "Toyota Supra",
  "brand": "Toyota",
  "year": 2022,
  "description": "Mobil sport legendaris",
  "image_url": "https://example.com/supra.jpg",
  "category": "Mobil Sport"
}

###

### Update Vehicle (Protected)
PUT http://localhost:5000/api/vehicles/1
Content-Type: application/json
Authorization: Bearer 

{
  "name": "Toyota Supra GR",
  "brand": "Toyota",
  "year": 2023,
  "description": "Update dengan teknologi GR",
  "image_url": "https://example.com/supra-gr.jpg",
  "category": "Mobil Sport"
}

###

### Delete Vehicle (Protected)
DELETE http://localhost:5000/api/vehicles/1
Authorization: Bearer 
